/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ACO;

import static ACO.load.hl1;
import static ACO.load.vl1;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Random;
import javax.swing.UIManager;
import org.cloudbus.cloudsim.Cloudlet;

/**
 *
 * @author EGC07
 */
public class allocation1 extends javax.swing.JFrame {
public static ArrayList ant=Vms.antpool;
public static ArrayList suhost=new ArrayList();
public static ArrayList antpool=new ArrayList();
public static ArrayList k=load.hostload;
public static ArrayList l=load.vmload;
String curr_load;
 String k1[];
    String k2[];
  public static ArrayList vl1=Vms.vla;
    public static ArrayList hl1=DataCenter_Brokers.hla;
    public static ArrayList ap1=Vms.antpool1;
    public static ArrayList suth=new ArrayList();
    public static ArrayList arrl=new ArrayList();
    public static double te=DataCenter_Brokers.time_zone;int step=0;
    String besthost;
     ArrayList ad = new ArrayList();
 double bestload;
    /**
     * Creates new form allocation1
     */
    public allocation1() 
    {
        initComponents();
       jScrollPane4.setVisible(false);
       jScrollPane5.setVisible(false);
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/sim.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setTitle("Allocation");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 180, 262, 181);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Host for VM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 380, 120, 50);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(280, 180, 280, 181);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Ant Pool");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(340, 380, 120, 50);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Ant");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(570, 380, 120, 50);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText(" ");
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(570, 180, 320, 181);

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(210, 100, 50, 65);

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(550, 80, 50, 73);

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setText("ALLOCATION");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(710, 380, 160, 50);

        jLabel1.setFont(new java.awt.Font("NSimSun", 1, 30)); // NOI18N
        jLabel1.setText("ANT ALLOCATIONS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 20, 320, 35);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/res_sap_2_01.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(640, -70, 430, 350);

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton6.setText("Proceed");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(750, 540, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 610);

        setSize(new java.awt.Dimension(916, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
      Class.forName("com.mysql.jdbc.Driver").newInstance();
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/aco?zeroDateTimeBehavior=convertToNull","root","");
      Statement stmt=con.createStatement();
      stmt.executeUpdate("DROP TABLE IF EXISTS sut_host"); 
      String create="create table sut_host(host_id varchar(50),v_id varchar(50))";
      stmt.execute(create);       
        
        
        
        
for(int h=0;h<ant.size();h++)
{
    System.out.println(ant.get(h));
   
}




 
String sql="select  host_id,vm_id from hvload a  join vload b where a.load_h>=b.load_v";    
    PreparedStatement pst=con.prepareStatement(sql);
    ResultSet rs=pst.executeQuery();
    jTextArea1.append("Host_id \t Vm_id\n");
     jTextArea1.append("**************************\n");
    while(rs.next())
    {
        String d=rs.getString(1);
        String d1=rs.getString(2);
       
       jTextArea1.append(d+"------------------>"+d1+"\n");
       suth.add(d+"\t"+d1);
    }
    
    
    

    }
    catch(Exception ed)
    {
    }

//for(int j=0;j<ant.size();j++)
//{
////    ant.get(j).toString();
//    if(ant.get(j).toString()==null)
//   {
//      antpool.add(Integer.parseInt(ant.get(j).toString()));
//   } 
//}
//   for(int i=0;i<antpool.size();i++)
//   {
//   System.out.println(antpool.get(i).toString());
//   }    
//        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jTextArea2.append("Ant  \t VM\n");
jTextArea2.append("******************************\n");
try{
for(int h=0;h<=ap1.size();h++)
        {
            jTextArea2.append(ap1.get(h).toString()+"\n");
        }
}
catch(Exception e)
{
    
}
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
String[] sp;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

System.out.println("host Load");
for(Object g:k)
{
//    System.out.println(g);
    jTextArea4.append(g+"\n");
   
}
for(Object h:l)
{
      jTextArea5.append(h+"\n");  
}

// try 
//        {
//          
//            String fin = tp.getText();
//            String df[] = fin.split("\n");
//            k = new String[df.length];
//            k1 = new String[df.length];
//            //            wlshow.setText("Arrived Work Load :"+"\n");
//            for (int i = 0; i < df.length; i++) 
//                {
//                    String spl[] = df[i].split("\t");
//                    k[i] = spl[1];
//                    k1[i] = spl[0];
//                //                wlshow.append(k1[i]+"\t"+k[i]+"\n");
//                }
//        } 
//        catch (Exception e) {
//            System.out.println(e);
//        }






 
 
 
 


System.out.println("vm load");
for(Object f:l)
{
    System.out.println(f);
}






double mutationRate=77786.0;
 String sql="";
 String nextHost;
   jTextArea3.append("Allocated_Host\t\tAllocate_VM\n");
        jTextArea3.append("**********************************\n");
      

  Random r=new Random();
  
        while (step<ap1.size())
        {
              curr_load=hl1.get(step).toString()+"\n";
//            sql="select * from hvload where host_id='"+hl1.get(step).toString()+"'";
           arrl.add(curr_load);
           if(r.nextInt()<mutationRate)
           {
              step++;
           }
           else
           {
               chooseNextstep();
           }
           
                   {
                  mutationRate=mutationRate-te;
                   }
            step++;
            System.out.println(suth.get(step).toString()+"\n");
        }
  
        
//        try
//        {
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/aco?zeroDateTimeBehavior=convertToNull [root on Default schema]","root","");
//            Statement st=con.createStatement();
//            ResultSet rs=st.executeQuery(sql);
//            while(rs.next())
//            {
//                String r=rs.getString(1);
//                String r1=rs.getString(2);
//                System.out.println(r);
//            }
//        }
//        catch(Exception e )
//        {
//            
//        }
//        
        

    
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
   try 
        {
//            jTextArea5.append("Cloud_Let \t  LOAD_BALANCE \t VM \n\n");
            String fin = jTextArea5.getText();
            String df[] = fin.split("\n");
            k1 = new String[df.length];
            k2 = new String[df.length];
            //            wlshow.setText("Arrived Work Load :"+"\n");
            for (int i = 0; i < df.length; i++) 
                {
                    String spl[] = df[i].split("\t");
                    k1[i] = spl[1];
                    k2[i] = spl[0];
                //                wlshow.append(k1[i]+"\t"+k[i]+"\n");
                }
        } 
        catch (Exception e) 
        {
            System.out.println(e);
        }
        
        
     try 
        {

          
            Cloudlet cldlet = null;
            String h[] = jTextArea4.getText().split("\n");

            String ak[] = new String[h.length];
            String id[] = new String[h.length];
            for (int k = 0; k < ak.length; k++) {

                String spl[] = h[k].split("\t");

                ak[k] = spl[1];
                id[k] = spl[0];

            }

            double j = 0;
            for (int i = 0; i < k1.length; i++) {

                double cal = Double.valueOf(k1[i]);
                double vv;
                int c = 0;
            System.out.println("iiiii");
                //               jTextArea4.append(cldlet.getExecStartTime()+"\t");
                for (int j1 = 0; j1 < id.length; j1++) 
                {

                    if (c == 0) 
                    {
                        double ca = Double.valueOf(ak[j1]);
//                           double ca = 0.0;
                        if (cal < ca) 
                        {

                            vv = ca - cal;
                            ak[j1] = String.valueOf(vv);
                            System.out.println(ak[j1]);
                            c = 1;
                            ad.add(k1[i]);
//                            jTextArea4.append("Cloud_Let"+k2[i] + "\t\t" + vv + "\t\t" + "VM_"+id[j1] + "\n\n");
                     
//                            jTextArea3.append("Hid_"+k2[i] +"\t\t" + "VM_"+id[j1] + "\n\n");
                            jTextArea3.append("HID_"+id[j1]+"\t\t"+"VID_"+k2[i]+"\n");
                        
                        }
                        //
                    }
                    //                   else
                    //                       {
                        //                            double ca=Double.valueOf(ak[j1]);
                        //                           vv=ca-cal;
                        //                           ak[j1]=String.valueOf(vv);
                        //                           System.out.println(ak[j1]);
                        //                           c=1;
                        //                           jTextArea4.append("PUBLIC"+k1[i]+"\t"+id[j1]+"\n\n");
                        //                       }

                }

            }
          

        } catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Joballocation1 s=new Joballocation1();
    s.setVisible(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed


@SuppressWarnings("empty-statement")
    public void chooseNextstep()
{
    besthost=suth.get(step).toString();
    bestload=Double.parseDouble(curr_load);
    for(int i=0;i<hl1.size();i++)
    {
        besthost=hl1.get(i).toString();
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try
        {
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        }
        catch(Exception e)
        {
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new allocation1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    // End of variables declaration//GEN-END:variables
}
