/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ACO;

import static ACO.Vms.vl;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.UIManager;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author EGC07
 */
public class load extends javax.swing.JFrame {
public static ArrayList vm=Vms.vmload;
    public static ArrayList allvm =new ArrayList();
    public static ArrayList vl1=Vms.vl;
    public static ArrayList hl1=DataCenter_Brokers.hl;
    public static ArrayList ram=Vms.vraml;
    public static ArrayList mip=Vms.vmipl;
    public static ArrayList hostload=new ArrayList();
    public static ArrayList vmload=new ArrayList();
    /**
     * Creates new form load
     */
    public load() {
        initComponents();
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/sim.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("VM & Host Allocations");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Virtual_Machine Load", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 131, 405, 234);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Host Load", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(460, 130, 426, 230);

        jLabel1.setFont(new java.awt.Font("NSimSun", 1, 30)); // NOI18N
        jLabel1.setText("VM AND HOST LOAD ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(290, 30, 340, 42);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(439, 101, 10, 270);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Proceed");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(740, 530, 120, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Load");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(390, 400, 120, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 600);

        setSize(new java.awt.Dimension(916, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       allocation1 d=new allocation1();
d.setVisible(true);
        
try
{
                 Class.forName("com.mysql.jdbc.Driver").newInstance();
                 Connection con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/aco?zeroDateTimeBehavior=convertToNull","root","");
                 Statement stmt=con1.createStatement();
                 stmt.executeUpdate("create table vload1 as select * from vload order by load_v desc");
             
    
}
catch(Exception e)
{
    System.out.println(e);
}
   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try
{
      Class.forName("com.mysql.jdbc.Driver").newInstance();
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/aco?zeroDateTimeBehavior=convertToNull","root","");
      Statement stmt=con.createStatement();
      
      stmt.executeUpdate("DROP TABLE IF EXISTS hvload"); 
      stmt.executeUpdate("DROP TABLE IF EXISTS vload"); 
      String create="create table hvload(host_id varchar(50),load_h int(50))";
      String create1="create table vload(vm_id varchar(50),load_v int(50))";
      stmt.execute(create);
      stmt.execute(create1);
//      PreparedStatement pst=con.prepareStatement(create);
         
       double vmLoad,allVmLoad=0;
        jTextArea1.append("VM_ID\tLOAD\n");
        jTextArea1.append("-------------------------------\n");
        
     for(int s=0;s<vl1.size();s++)
        {
            jTextArea1.append(vl1.get(s).toString()+"\n");
            vmload.add(vl1.get(s));
        }
     
   for(Object s:hl1)
   {
       int i=0;int j=0;
       String sd=(String)s;
       String spl[]=sd.split("\t");
       if(i==0)
       {
           System.out.println(spl[0]);
           String sql1="insert into hvload(host_id,load_h)values('"+spl[0]+"','"+spl[1]+"')";
           stmt.executeUpdate(sql1);
//           JOptionPane.showMessageDialog(this, "success");
         
       }

       i++;
       
   }
//           System.out.println("row inserted"+i);
        
 
       jTextArea2.append("Host_ID\tLOAD\n");
        jTextArea2.append("---------------------------------\n");
        
     for(int s=0;s<hl1.size();s++)
        {
        jTextArea2.append(hl1.get(s).toString()+"\n");
        hostload.add(hl1.get(s));
        }
 for(Object s:vl1)
   {
       int i=0;int j=0;
       String sd=(String)s;
       String spl[]=sd.split("\t");
       if(i==0)
       {
           System.out.println(spl[0]);
           String sql1="insert into vload(vm_id,load_v)values('"+spl[0]+"','"+spl[1]+"')";
           stmt.executeUpdate(sql1);
//           JOptionPane.showMessageDialog(this, "success");
         
       }

       i++;
       
   }
       
//       for(int i=0;i<vm.size();i++)
//                {
//                 spl = vm.get(i).toString().split(":");                
//
//                   
//                    
//                    allVmLoad+=vmLoad;
//                   
//                     allvm.add(allVmLoad);
//                    
//                    jTextArea1.append(h.getId()+"\t"+h.getVmm()+"\t"+allVmLoad+"\n\n");
//                    
//                    
//                }
       
   
    
}
catch(Exception e)
{
    System.out.println(e);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
          try
        {
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        }
        catch(Exception e)
        {
            
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new load().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
