/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ACO;

import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.UIManager;

/**
 *
 * @author EGC07
 */
public class Load_Table extends javax.swing.JFrame {
public static ArrayList d=DataCenter_Brokers.k;
public static ArrayList v=Vms.vmload;

    /**
     * Creates new form Load_Table
     */
    public Load_Table() {
        initComponents();
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/sim.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Load_Table");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("NSimSun", 1, 30)); // NOI18N
        jLabel1.setText("Overall Load");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 20, 310, 42);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 180, 400, 223);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(470, 180, 420, 223);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(267, 380, 403, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1389441062_DAF_Tipper_Container_Truck.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 30, 230, 185);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(440, 190, 30, 210);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(750, 530, 107, 40);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Calculate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(390, 460, 112, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(911, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            try
        {
            //=================Load Schl of VM=========================
            List vmList=new ArrayList();
            ArrayList vDetails=new ArrayList();
            int tVms;
            double vmLoad,allVmLoad=0;
            
            jTextArea1.append("Vm_Id\tBw\tRAM\tMIPs\tNo.PEs\n");
            jTextArea1.append("==============================================================\n\n");
            jTextArea2.append("h_id\tRam\tStorage\tBw\tNo.pes\n"+
                              "======================================================\n\n");
            for(int j=0;j<v.size();j++)
            {
                jTextArea1.append(v.get(j).toString()+"\n");
            }
            for(int k=0;k<d.size();k++)
            {
                  jTextArea2.append(d.get(k).toString()+"\n");
            }
//            for(int j=0;j<broker.length;j++)
//            {
//                vmList=broker[j].getVmList();
//                tVms=vmList.size();
//                for(int i=0;i<vmList.size();i++)
//                {
//                    org.cloudbus.cloudsim.Vm h=(org.cloudbus.cloudsim.Vm)vmList.get(i);                    
//                    vDetails.add("id: "+h.getId()+
//                            "\tvmUid : "+h.getUid()+
//                            "\tbw : "+h.getBw()+
//                            "\tram : "+h.getRam()+
//                            "\tmips : "+h.getMips()+
//                            "\tnpes : "+h.getNumberOfPes());
//                   
//                    vmLoad=h.getBw()+h.getRam()+h.getMips();
//                    allVmLoad+=vmLoad;
//                    jTextArea1.append(h.getId()+
//                            "\t"+h.getUid()+
//                            "\t"+h.getBw()+
//                            "\t"+h.getRam()+
//                            "\t"+h.getMips()+
//                            "\t"+h.getNumberOfPes()+"\n\n");
//                }
//                allvm.add(allVmLoad);
//                jTextArea2.append(j+"\t"+broker[j].getId()+"\t"+tVms+"\t"+allVmLoad+"\n\n");
//                BrokerLoad.add(allVmLoad);
//                allVmLoad=0;
//            }
        }
        catch(Exception e)
        {
            System.out.println("Exception : "+e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      load d=new load();
d.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try
        {
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        }
        catch(Exception e)
        {
            
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Load_Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
